version: "3.9"
services:
  ldap:
    # https://github.com/bitnami/bitnami-docker-openldap
    image: bitnami/openldap:latest
    ports:
      - "127.0.0.1:1389:1389"
    volumes:
      - ldap:/bitnami/openldap/
    environment:
      LDAP_ROOT: dc=mbo,dc=dev
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_USERS: sample01
      LDAP_PASSWORDS: samplepassword
      LDAP_USER_DC: users
      LDAP_GROUP: readers
      LDAP_ADD_SCHEMAS: "yes"
      LDAP_EXTRA_SCHEMAS: cosine,inetorgperson,nis
      LDAP_ULIMIT_NOFILES: 1024
      LDAP_ALLOW_ANON_BINDING: "no"
      LDAP_ENABLE_TLS: "no"
      ALLOW_EMPTY_PASSWORD: "no"
volumes:
  ldap:


